import React from "react";
import Head from "next/head";
import Link from "next/link";
import { Splide, SplideSlide } from "@splidejs/react-splide";
import "@splidejs/react-splide/css";
import YoutubeEmbed from "../components/YoutubeEmbed";
import ContactForm from "@/components/ContactForm";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Testbytes: Software Testing and QA Consulting Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="image"
          property="og:image"
          content="/images/TestBytes_OG.jpg"
        />
        <meta property="og:url" content="https://www.testbytes.net/" />
        <meta property="og:type" content="website" />
        <meta
          property="og:title"
          content="Testbytes: Software Testing and QA Consulting Company"
        />
        <meta
          property="og:description"
          content="Looking for independent software testing services? Testbytes can offer game testing, mobile app testing, security testing, performance testing, and more."
        />
      </Head>


                  <div className="innerpages-maintop-banner">
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-7">
                                <h1>Contact Us</h1>
                               
                                    <h3></h3>
                              
                            </div>
                            <div className="col-lg-5">
                                
                                    <div className="innerpages-maintop-banner-imgwith-mask">
                                        <div>
                                            <img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/uploads/2023/08/ut_img.png" alt=""/>
                                        </div>
                                    </div>
                                
                            </div>
                        </div>
                    </div>
                </div>

      <div className="contact_form">
        <div className="container">
          <div className="offset-lg-3 col-lg-6">
            <ContactForm />
          </div>
        </div>
      </div>
      <div class="contact_details">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <div class="contact_item">
                <Link href="mailto:info@testbytes.net">
                  <img
                    src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/mail-id.png"
                    alt=""
                  />
                  <div class="contact_item1">
                    <h4>E-MAIL US</h4>
                    <p>info@testbytes.net</p>
                  </div>
               </Link>
              </div>
            </div>
            <div class="col-sm-4">
              <Link href="tel:+1 929 552 0053">
                <div class="contact_item">
                  <img
                    src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/phone.png"
                    alt=""
                  />
                  <div class="contact_item1">
                    <h4>PHONE</h4>
                    <p>+1 929 552 0053 </p>
                  </div>
                </div>
             </Link>
            </div>
            <div class="col-sm-4">
              <Link href="https://api.whatsapp.com/send?phone=19295521900 ">
                <div class="contact_item">
                  <img
                    src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/whatsapp.png"
                    alt=""
                  />
                  <div class="contact_item1">
                    <h4>whatsapp</h4>
                    <p>19295521900 </p>
                  </div>
                </div>
             </Link>
            </div>
          </div>
        </div>
      </div>
      <div className="address_details"> 
		<div class="container">
			<h2>Our Offices</h2>
			<div class="row">
				<div class="col-md-6">
					<div class="row">
						<div class="col-md-6">
							<div class="img_wrapper">
								<img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/uploads/2023/09/taj.jpg" alt=""/>
							</div>
						</div>
						<div class="col-md-6">
							<div class="img_wrapper conatct_flag">
									<h3><img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/uploads/2023/09/indian-flag-png.png" alt="India-image"/>  India</h3>
								<p>Kalas road, Vishrantwadi, <br />Pune, Maharashtra-411015</p>
								<p class="ml_det"><i class="fa fa-envelope"></i> info@testbytes.net</p>
								<p class="ml_det"><i class="fa fa-phone"></i> +1 929 552 0053  </p>
								
							</div>
						</div>
					</div>
				</div>
				
				<div class="col-md-6">
					<div class="row">
						<div class="col-md-6">
							<div class="img_wrapper">
								<img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/uploads/2023/09/white-house.jpg" alt=""/>
							</div>
						</div>
						<div class="col-md-6">
							<div class="img_wrapper conatct_flag">
									<h3><img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/uploads/2023/09/USA-flag.jpg" alt="UK-image"/> USA</h3>
								<p>65 Broadway Suite 1101,<br /> New York NY 10006
								</p>
								<p class="ml_det"><i class="fa fa-envelope"></i> info@testbytes.net</p> 
								<p class="ml_det"><i class="fa fa-phone"></i> +1 929 552 0053</p>
							</div>
						</div>
					</div>
				</div>
				
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="social_med_07">
						<h4>Stay connected with us</h4>
						<a href="https://www.facebook.com/TestbytesSoftwareTestingCompany/" target="_blank">
						 <img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/Facebook.png" alt=""/>
						</a>

						<a href="https://twitter.com/testbytes" target="_blank">
							<img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/twitter.png" alt=""/>
						</a>

						<a href="https://www.linkedin.com/company/testbytes/" target="_blank">
						 <img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/linkedln.png" alt=""/>
					
						</a>

						<a href="https://www.youtube.com/channel/UCS0vvkVPQgsj7ql9UKpSmGA" target="_blank">
						 <img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/youtube.png" alt=""/>	

						</a>

						<a href="https://in.pinterest.com/testbytes/" target="_blank">
						 <img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/pinterest.png" alt=""/>
						</a>

						<a href="https://www.instagram.com/testbytes_testing_company/" target="_blank">
						 <img src="https://testbytesnxtjsbackend.technoallianceindia.com/wp-content/themes/testbyteswp-backend/images/instagram.png" alt=""/>
						</a>
					</div>
					
				</div>
			</div>
		</div> 
      </div>
    </>
  );
}
